# Default initial positions for panda's ros2_control fake system

initial_positions:
  panda_finger_joint1: 0
  panda_joint1: 0
  panda_joint2: -0.7850
  panda_joint3: 0
  panda_joint4: -2.3560
  panda_joint5: 0
  panda_joint6: 1.5710
  panda_joint7: 0.7850
